version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql

  backend:
    image: backend
    build: .
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
    command: "yarn start:dev"
    depends_on:
      - mysqldb
