name: Release & Build
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install the dependencies
        run: yarn install --frozen-lockfile
      - name: Initialize Git user
        run: |
          git config --global user.email "wendel.luiz.profissional@gmail.com"
          git config --global user.name "Release Workflow"
      - name: Run Release
        run: yarn release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Success
        run: echo 'Success!'
